services:
  - type: web
    name: excel-unlocker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
    plan: free
    disk:
      name: excel-unlocker-disk
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
